### ISSUE TITLE
Set environment variable replaces all configuration

### ISSUE THREAD

**Issue by pedrocwb** [beetbox/confuse#143]
There seems to be a problem with `set_env` feature since it is replacing configs present in the config_default.yaml even if no environment variable is set. 

See the examples:
```
config_default.yaml
app_name: foo
foo:
  bar: awesome_app
```

```
import confuse
config = confuse.Configuration("main", __name__)
config.set_file("config_default.yaml")
print("Without set_env")
print(config.get())

> Without set_env
> {'app_name': 'foo', 'foo': OrderedDict([('bar', 'awesome_app')])}
```

```
import confuse
config = confuse.Configuration("main", __name__)
config.set_file("config_default.yaml")
config.set_env()
print("With set_env ")
print(config.get())

>With set_env 
> {}
```

**Comment by arroyoj** [comment]
@pedrocwb, thanks for testing out the new `set_env` function and reporting this issue. I think I can explain what is going on.

When `set_env` is called and the environment variables are not set, an empty `ConfigSource` is created at the top of the config stack. Calling `config.get()` with no parameters will retrieve whatever source is at the top of the stack, which in this case will be empty. You can produce similar behavior without `set_env`. For example, if you try loading an empty yaml file on top of the example config_default.yaml file you defined above:
```
touch empty.yaml
```

```
import confuse
config = confuse.Configuration("main", __name__)
config.set_file("config_default.yaml")
print("Default")
print(config.get())

> Default
> {'app_name': 'foo', 'foo': OrderedDict([('bar', 'awesome_app')])}

config.set_file("empty.yaml")
print("With empty.yaml")
print(config.get())

> With empty.yaml
> {}
```

You would also get similar behavior if you had a command line parser with arguments not present in config_default.yaml:

```
import confuse
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--not-in-config')
args = parser.parse_args()
config = confuse.Configuration("main", __name__)
config.set_file("config_default.yaml")
config.set_args(args)
print("With wrong args")
print(config.get())

> With wrong args
> {}
```

I think there are two solutions to this issue:

1. Use a template with `get`. This will tell confuse what keys to look for, and it will search down through the sources to find them, ignoring the empty source at the top of the stack from the call to `set_env`:

```
import confuse
config = confuse.Configuration("main", __name__)
config.set_file("config_default.yaml")
config.set_env()
print("With template")
print(config.get({'app_name': str, 'foo': {'bar': str}}))

> With template 
> {'app_name': 'foo', 'foo': {'bar': 'awesome_app'}}
```

2. If you don't want to use a template and just want to get "everything" from the top level down without telling confuse what to look for, then you can use `flatten` instead of `get`. Note that with `flatten`, higher priority sources can still hide nested keys in lower sources (not shown here), but empty sources will not hide lower sources:

```
import confuse
config = confuse.Configuration("main", __name__)
config.set_file("config_default.yaml")
config.set_env()
print("With flatten")
print(config.flatten())

> With flatten
> OrderedDict([('app_name', 'foo'), ('foo', OrderedDict([('bar', 'awesome_app')]))])
```

@sampsyo, how do you think we should resolve this issue? Technically, I think it would be possible to change `set_env` to explicitly check if the source is empty and only add it to the stack if it contains values. However, that would make `set_env` work differently from `set_file` and `set_args`, which have no such check. I think my preference would be to update the docs for `set_env` to point out the issue @pedrocwb identified and provide the two approaches above as solutions. Happy to submit a PR either way.

**Comment by sampsyo** [comment]
Awesome explanation; thanks for the details, @arroyoj. I hadn't thought carefully enough to realize that this is just the way that `config.get()` works! It's possible we can concoct a way to document this better, but it's hard to explain beyond the fundamental "theory" that's currently in the docs.

**Comment by arroyoj** [comment]
@sampsyo, I'm thinking maybe we just need a "note" or "warning" box somewhere, either in the view section or maybe the environment variables section. In addition to the explanation of the theory that is already in the docs, it could just call out some common "gotchas" like calling `get` at the top level with no template, when the user probably meant `flatten`. If I have some time, I'll try to put something together and submit a PR.

**Comment by sampsyo** [comment]
Sure; that's a good idea! I kinda thing the view section would be the right place—it could even reference stuff like `set_env` and `set_args` as the most likely routes to encountering this pitfall.

**Comment by pedrocwb** [comment]
Thank you @arroyoj  and @sampsyo. It made a lot clear to me. In my case, it makes more sense to use flatten the configs.
