### ISSUE TITLE
confuse.Number() does not work with numbers in scientific notation

### ISSUE THREAD

**Issue by tomaszchabinka** [beetbox/confuse#155]
Hey, in my yaml file I have something like this:

`number_between_0_and_1: 5e-4`

I can load my yaml file with confuse and do following:

`assert float(config["number_between_0_and_1: 5e-4"].get()) == 0.0005`

but following code will raise exception:

`assert config["number_between_0_and_1: 5e-4"].get( confuse.Number() ) == 0.0005`:

confuse.exceptions.ConfigTypeError: number_between_0_and_1: must be numeric, not str

Could the behaviour of confuse.Number() be changed, so it's consistent with float() parsing of numbers written in scientific notation?

**Comment by sampsyo** [comment]
Interesting! The issue here would actually not be with confuse itself, but with PyYAML (the YAML parser library). You could try diagnosing what the YAML parser sees in isolation, like this:

```
$ python3 -c 'import yaml; print(type(yaml.safe_load("5e-4")))'
<class 'str'>
```

Glancing at the YAML spec led me to try this instead:

```
$ python3 -c 'import yaml; print(type(yaml.safe_load("5.0e-4")))'
<class 'float'>
```

So try adding that `.0` and you should be good to go.
